import appetizers from './icons/appetizers.png';
import children from './icons/children.png';
import desserts from './icons/desserts.png';
import drinks from './icons/drinks.png';
import first from './icons/first.png';
import grilled from './icons/grilled.png';
import national from './icons/national.png';
import salads from './icons/salads.png';
import sauces from './icons/sauces.png';
import second from './icons/second.png';
import therapeutic from './icons/therapeutic.png';
import vegans_icon from './icons/vegans.png';
import workpieces from './icons/workpieces.png';
import { NavItem } from './types';

export const NAVIGATION_ITEMS: NavItem[] = [
    {
        icon: salads,
        text: 'Салаты',
        link: 'salads',
        tabs: [
            { link: 'meat-salads', text: 'Мясные закуски' },
            { link: 'fish-salads', text: 'Рыбные салаты' },
            { link: 'vegetables-salads', text: 'Овощные салаты' },
            { link: 'warm-salads', text: 'Теплые салаты' },
        ],
    },
    {
        icon: appetizers,
        text: 'Закуски',
        link: 'appetizers',
        tabs: [
            { link: 'meat-appetizers', text: 'Мясные закуски' },
            { link: 'fish-appetizers', text: 'Рыбные закуски' },
            { link: 'vegetable-appetizers', text: 'Овощные закуски' },
            { link: 'warm-appetizers', text: 'Теплые закуски' },
            { link: 'sandwiches', text: 'Бутерброды' },
            { link: 'fastfood', text: 'Фастфуд' },
        ],
    },
    {
        icon: first,
        text: 'Первые блюда',
        link: 'soups',
        tabs: [
            { link: 'meat-soups', text: 'Мясные супы' },
            { link: 'vegetable-soups', text: 'Овощные супы' },
            { link: 'broths', text: 'Бульоны' },
            { link: 'cold-soups', text: 'Холодные супы' },
            { link: 'diet-soups', text: 'Диетические супы' },
        ],
    },
    {
        icon: second,
        text: 'Вторые блюда',
        link: 'second',
        tabs: [
            { link: 'meat', text: 'Мясные' },
            { link: 'fish', text: 'Рыбные' },
            { link: 'vegetable', text: 'Овощные' },
            { link: 'poultry', text: 'Из птицы' },
            { link: 'mushrooms', text: 'Из грибов' },
            { link: 'offal', text: 'Из субпродуктов' },
            { link: 'steamed', text: 'На пару' },
            { link: 'dumplings', text: 'Пельмени, вареники' },
            { link: 'flour-side', text: 'Мучные гарниры' },
            { link: 'vegetable-side', text: 'Овощные гарниры' },
            { link: 'pizza', text: 'Пицца' },
            { link: 'sushi', text: 'Суши' },
        ],
    },
    {
        icon: desserts,
        text: 'Десерты, выпечка',
        link: 'desserts',
        tabs: [
            { link: 'pancakes', text: 'Блины и оладьи' },
            { link: 'pies', text: 'Пироги и пончики' },
            { link: 'cakes', text: 'Торты' },
            { link: 'rolls', text: 'Рулеты' },
            { link: 'muffins', text: 'Кексы и маффины' },
            { link: 'cheesecakes', text: 'Сырники и ватрушки' },
            { link: 'puff-pastry', text: 'Из слоеного теста' },
            { link: 'choux-pastry', text: 'Из заварного теста' },
            { link: 'yeast-dough', text: 'Из дрожжевого теста' },
            { link: 'buns', text: 'Булочки и сдоба' },
            { link: 'bread', text: 'Хлеб' },
            { link: 'pizza-dough', text: 'Тесто на пиццу' },
            { link: 'creams', text: 'Кремы' },
        ],
    },
    {
        icon: grilled,
        text: 'Блюда на гриле',
        link: 'grilled',
        tabs: [
            { link: 'grilled-beef', text: 'Говядина' },
            { link: 'grilled-pork', text: 'Свинина' },
            { link: 'grilled-poultry', text: 'Птица' },
            { link: 'grilled-fish', text: 'Рыба' },
            { link: 'grilled-mushrooms', text: 'Грибы' },
            { link: 'grilled-vegetables', text: 'Овощи' },
        ],
    },
    {
        icon: vegans_icon,
        text: 'Веганская кухня',
        link: 'vegans',
        tabs: [
            { link: 'appetizers', text: 'Закуски' },
            { link: 'first', text: 'Первые блюда' },
            { link: 'second', text: 'Вторые блюда' },
            { link: 'side_dishes', text: 'Гарниры' },
            { link: 'desserts', text: 'Десерты' },
            { link: 'pastries', text: 'Выпечка' },
            { link: 'raw_food', text: 'Сыроедческие блюда' },
            { link: 'drinks', text: 'Напитки' },
        ],
    },
    {
        icon: children,
        text: 'Детские блюда',
        link: 'kids',
        tabs: [
            { link: 'kids-first', text: 'Первые блюда' },
            { link: 'kids-second', text: 'Вторые блюда' },
            { link: 'kids-side', text: 'Гарниры' },
            { link: 'kids-bakery', text: 'Выпечка' },
            { link: 'kids-gluten-free', text: 'Без глютена' },
            { link: 'kids-sugar-free', text: 'Без сахара' },
            { link: 'kids-allergen-free', text: 'Без аллергенов' },
            { link: 'kids-baby-food', text: 'Блюда для прикорма' },
        ],
    },
    {
        icon: therapeutic,
        text: 'Лечебное питание',
        link: 'therapeutic',
        tabs: [
            { link: 'kids-diet', text: 'Детская диета' },
            { link: 'diet-1', text: 'Диета №1' },
            { link: 'diet-2', text: 'Диета №2' },
            { link: 'diet-3', text: 'Диета №3' },
            { link: 'diet-5', text: 'Диета №5' },
            { link: 'diet-6', text: 'Диета №6' },
            { link: 'diet-7', text: 'Диета №7' },
            { link: 'diet-8', text: 'Диета №8' },
            { link: 'diet-9', text: 'Диета №9' },
            { link: 'diet-10', text: 'Диета №10' },
            { link: 'diet-11', text: 'Диета №11' },
            { link: 'diet-12', text: 'Диета №12' },
            { link: 'diet-13', text: 'Диета №13' },
            { link: 'diet-14', text: 'Диета №14' },
            { link: 'gluten-free', text: 'Без глютена' },
            { link: 'allergen-free', text: 'Без аллергенов' },
        ],
    },
    {
        icon: national,
        text: 'Национальные',
        link: 'national',
        tabs: [
            { link: 'american', text: 'Американская кухня' },
            { link: 'armenian', text: 'Армянская кухня' },
            { link: 'greek', text: 'Греческая кухня' },
            { link: 'georgian', text: 'Грузинская кухня' },
            { link: 'italian', text: 'Итальянская кухня' },
            { link: 'spanish', text: 'Испанская кухня' },
            { link: 'chinese', text: 'Китайская кухня' },
            { link: 'mexican', text: 'Мексиканская кухня' },
            { link: 'panasian', text: 'Паназиатская кухня' },
            { link: 'russian', text: 'Русская кухня' },
            { link: 'turkish', text: 'Турецкая кухня' },
            { link: 'french', text: 'Французская кухня' },
            { link: 'swedish', text: 'Шведская кухня' },
            { link: 'japanese', text: 'Японская кухня' },
            { link: 'other-cuisine', text: 'Другая кухня' },
        ],
    },
    {
        icon: sauces,
        text: 'Соусы',
        link: 'sauces',
        tabs: [
            { link: 'meat-sauces', text: 'Соусы мясные' },
            { link: 'cheese-sauces', text: 'Соусы сырные' },
            { link: 'marinades', text: 'Маринады' },
            { link: 'preserves', text: 'Домашние заготовки' },
            { link: 'meat-preserves', text: 'Мясные заготовки' },
            { link: 'fish-preserves', text: 'Рыбные заготовки' },
            { link: 'cucumber-preserves', text: 'Из огурцов' },
            { link: 'tomato-preserves', text: 'Из томатов' },
            { link: 'mushroom-preserves', text: 'Из грибов' },
            { link: 'vegetable-preserves', text: 'Овощные заготовки' },
            { link: 'salads-preserves', text: 'Салаты, икра' },
            { link: 'fruit-preserves', text: 'Из фруктов и ягод' },
        ],
    },
    {
        icon: drinks,
        text: 'Напитки',
        link: 'drinks',
        tabs: [
            { link: 'juices', text: 'Соки и фреши' },
            { link: 'smoothies', text: 'Смузи' },
            { link: 'compotes', text: 'Компоты' },
            { link: 'kissels', text: 'Кисели' },
            { link: 'coffee', text: 'Кофе' },
            { link: 'tea', text: 'Лечебный чай' },
            { link: 'kvass', text: 'Квас' },
            { link: 'cocktails', text: 'Коктейли' },
            { link: 'alcohol', text: 'Алкогольные' },
        ],
    },
    {
        icon: workpieces,
        text: 'Заготовки',
        link: 'preserves',
        tabs: [
            { link: 'meat-preserves', text: 'Мясные заготовки' },
            { link: 'fish-preserves', text: 'Рыбные заготовки' },
            { link: 'cucumber-preserves', text: 'Из огурцов' },
            { link: 'tomato-preserves', text: 'Из томатов' },
            { link: 'mushroom-preserves', text: 'Из грибов' },
            { link: 'vegetable-preserves', text: 'Овощные заготовки' },
            { link: 'salads-preserves', text: 'Салаты, икра' },
            { link: 'fruit-preserves', text: 'Из фруктов и ягод' },
        ],
    },
];
export const NAVIGATION_ITEMS_LINKS = NAVIGATION_ITEMS.map((item) => item.link);
