import { Recipe } from '~/types';

export const RECIPES: Recipe[] = [
    {
        id: '0',
        title: 'Картошка, тушенная с болгарским перцем и фасолью в томатном соусе',
        description:
            'Картошка, тушенная с болгарским перцем, фасолью, морковью и луком, - вариант сытного блюда на каждый день. Фасоль в данном случае заменяет мясо, делая рагу сытным и питательным. Чтобы сократить время приготовления, возьмём консервированную фасоль. Блюдо хоть и простое, но в полной мере наполнено ароматами и имеет выразительный вкус за счёт добавления томатной пасты.',
        category: ['vegan', 'second-dish'],
        subcategory: ['snacks', 'vegetables'],
        image: '/src/assets/images/solyanka.jpg',
        bookmarks: 85,
        likes: 152,
        date: '2025-02-28T00:00:00Z',
        time: '40 минут',
        portions: 2,
        nutritionValue: { calories: 250, proteins: 5, fats: 8, carbohydrates: 40 },
        ingredients: [
            { title: 'картошка', count: '4', measureUnit: 'шт.' },
            { title: 'болгарский перец', count: '2', measureUnit: 'шт.' },
            { title: 'фасоль', count: '200', measureUnit: 'г' },
            { title: 'томатный соус', count: '200', measureUnit: 'мл' },
            { title: 'лук', count: '1', measureUnit: 'шт.' },
            { title: 'специи', count: '0', measureUnit: 'по вкусу' },
        ],
        steps: [
            {
                stepNumber: 1,
                description: 'Нарезать картошку и перец.',
                image: 'url',
            },
            {
                stepNumber: 2,
                description: 'Обжарить лук до золотистого цвета.',
                image: 'url',
            },
            {
                stepNumber: 3,
                description: 'Добавить картошку, перец и фасоль, залить соусом.',
                image: 'url',
            },
            {
                stepNumber: 4,
                description: 'Тушить на медленном огне 30 минут.',
                image: 'url',
            },
        ],
        meat: '',
        side: 'potatoes',
    },
    {
        id: '1',
        title: 'Картофельные рулетики с грибами',
        description:
            'Рекомендую всем приготовить постное блюдо из картофеля и грибов. Готовится это блюдо без яиц, без мяса и без сыра, из самых простых ингредиентов, а получается очень вкусно и сытно. Постный рецепт картофельных рулетиков с грибами, в томатном соусе, - на обед, ужин и даже на праздничный стол!',
        category: ['vegan', 'snacks'],
        subcategory: ['snacks', 'warm-snacks'],
        image: '/src/assets/images/solyanka.jpg',
        bookmarks: 85,
        likes: 152,
        date: '2024-02-20T00:00:00Z',
        time: '30 минут',
        portions: 2,
        nutritionValue: { calories: 180, proteins: 4, fats: 6, carbohydrates: 28 },
        ingredients: [
            { title: 'картошка', count: '3', measureUnit: 'шт.' },
            { title: 'грибы', count: '200', measureUnit: 'г' },
            { title: 'мука', count: '100', measureUnit: 'г' },
            { title: 'специи', count: '0', measureUnit: 'по вкусу' },
        ],
        steps: [
            {
                stepNumber: 1,
                description: 'Отварить картошку и сделать пюре.',
                image: 'url',
            },
            {
                stepNumber: 2,
                description: 'Обжарить грибы до готовности.',
                image: 'url',
            },
            {
                stepNumber: 3,
                description: 'Сформировать рулетики и обжарить.',
                image: 'url',
            },
        ],
        side: 'potatoes',
    },
    {
        id: '2',
        title: 'Овощная лазанья из лаваша',
        description:
            'Большое, сытное блюдо для ценителей блюд без мяса! Такая лазанья готовится с овощным соусом и соусом бешамель, а вместо листов для лазаньи используется тонкий лаваш.',
        category: ['vegan', 'second-dish', 'national'],
        subcategory: ['second-dish', 'vegetables', 'italian', 'snacks'],
        image: '/src/assets/images/solyanka.jpg',
        bookmarks: 85,
        likes: 152,
        date: '2023-01-25T00:00:00Z',
        time: '1 час',
        portions: 1,
        nutritionValue: { calories: 300, proteins: 12, fats: 8, carbohydrates: 45 },
        ingredients: [
            { title: 'лаваш', count: '3', measureUnit: 'листов' },
            { title: 'овощной соус', count: '300', measureUnit: 'мл' },
            { title: 'соус бешамель', count: '200', measureUnit: 'мл' },
            { title: 'сыр', count: '100', measureUnit: 'г' },
        ],
        steps: [
            {
                stepNumber: 1,
                description: 'Приготовить соусы.',
                image: 'url',
            },
            {
                stepNumber: 2,
                description: 'Сложить слои лазаньи.',
                image: 'url',
            },
            {
                stepNumber: 3,
                description: 'Запекать 30 минут.',
                image: 'url',
            },
        ],
    },
    {
        id: '3',
        title: 'Тефтели из булгура и чечевицы, запечённые в томатном соусе',
        description:
            'Тефтели из булгура и чечевицы – яркие и питательные, отлично подходят для постного и вегетарианского меню. Тефтели получаются нежными, а также сочными и ароматными благодаря использованию томатного соуса и душистых пряностей.',
        category: ['vegan', 'second-dish'],
        subcategory: ['second-dish', 'poultry-dish'],
        image: '/src/assets/images/solyanka.jpg',
        bookmarks: 85,
        likes: 152,
        date: '2023-02-15T00:00:00Z',
        time: '50 минут',
        portions: 4,
        nutritionValue: { calories: 200, proteins: 10, fats: 5, carbohydrates: 30 },
        ingredients: [
            { title: 'булгур', count: '150', measureUnit: 'г' },
            { title: 'чечевица', count: '100', measureUnit: 'г' },
            { title: 'томатный соус', count: '200', measureUnit: 'мл' },
            { title: 'лук', count: '1', measureUnit: 'шт.' },
        ],
        steps: [
            {
                stepNumber: 1,
                description: 'Смешать булгур и чечевицу.',
                image: 'url',
            },
            {
                stepNumber: 2,
                description: 'Сформировать тефтели и запечь.',
                image: 'url',
            },
            {
                stepNumber: 3,
                description: 'Подавать с соусом.',
                image: 'url',
            },
        ],
    },
    {
        id: '4',
        title: 'Чесночная картошка',
        description:
            'Такая картошечка украсит любой семейный обед! Все будут в полном восторге, очень вкусно! Аромат чеснока, хрустящая корочка на картошечке - просто объедение! Отличная идея для обеда или ужина, готовится просто!',
        category: ['vegan', 'second-dish'],
        subcategory: ['side-dishes', 'second-dish', 'vegetables'],
        image: '/src/assets/images/solyanka.jpg',
        bookmarks: 124,
        likes: 342,
        date: '2024-03-01T00:00:00Z',
        time: '30 минут',
        portions: 2,
        nutritionValue: { calories: 220, proteins: 4, fats: 7, carbohydrates: 35 },
        ingredients: [
            { title: 'картошка', count: '6', measureUnit: 'шт.' },
            { title: 'чеснок', count: '5', measureUnit: 'зубчиков' },
            { title: 'масло', count: '50', measureUnit: 'мл' },
            { title: 'специи', count: '0', measureUnit: 'по вкусу' },
        ],
        steps: [
            {
                stepNumber: 1,
                description: 'Очистить и нарезать картошку.',
                image: 'url',
            },
            {
                stepNumber: 2,
                description: 'Обжарить с чесноком.',
                image: 'url',
            },
            {
                stepNumber: 3,
                description: 'Подавать горячей.',
                image: 'url',
            },
        ],
        side: 'potatoes',
    },
    {
        id: '5',
        title: 'Капустные котлеты',
        description:
            'Капустные котлеты по этому рецепту получаются необычайно пышными и невероятно вкусными. Мягкий вкус и лёгкая пряная нотка наверняка помогут сделать эти чудесные котлеты из капусты одним из ваших любимых овощных блюд.',
        category: ['vegan'],
        subcategory: ['second-dish', 'snacks'],
        image: '/src/assets/images/solyanka.jpg',
        bookmarks: 2,
        likes: 1,
        date: '2024-02-05T00:00:00Z',
        time: '35 минут',
        portions: 4,
        nutritionValue: { calories: 150, proteins: 5, fats: 4, carbohydrates: 20 },
        ingredients: [
            { title: 'капуста', count: '300', measureUnit: 'г' },
            { title: 'мука', count: '50', measureUnit: 'г' },
            { title: 'специи', count: '0', measureUnit: 'по вкусу' },
        ],
        steps: [
            {
                stepNumber: 1,
                description: 'Нарезать капусту и отварить.',
                image: 'url',
            },
            {
                stepNumber: 2,
                description: 'Смешать с мукой и сформировать котлеты.',
                image: 'url',
            },
            {
                stepNumber: 3,
                description: 'Обжарить до золотистой корочки.',
                image: 'url',
            },
        ],
    },
    {
        id: '6',
        title: 'Овощное рагу',
        description: 'Сытное рагу из сезонных овощей, приправленное травами.',
        category: ['vegan', 'second-dish'],
        subcategory: ['side-dishes', 'vegetables', 'snacks'],
        image: '/src/assets/images/solyanka.jpg',
        bookmarks: 8,
        likes: 60,
        date: '2023-03-12T00:00:00Z',
        time: '1 час',
        portions: 2,
        nutritionValue: { calories: 200, proteins: 5, fats: 8, carbohydrates: 30 },
        ingredients: [
            { title: 'цуккини', count: '1', measureUnit: 'шт.' },
            { title: 'болгарский перец', count: '1', measureUnit: 'шт.' },
            { title: 'морковь', count: '1', measureUnit: 'шт.' },
            { title: 'картошка', count: '2', measureUnit: 'шт.' },
            { title: 'специи', count: '0', measureUnit: 'по вкусу' },
        ],
        steps: [
            {
                stepNumber: 1,
                description: 'Нарезать все овощи.',
                image: 'url',
            },
            {
                stepNumber: 2,
                description: 'Обжарить на сковороде.',
                image: 'url',
            },
            {
                stepNumber: 3,
                description: 'Добавить специи и тушить до готовности.',
                image: 'url',
            },
        ],
    },

    {
        id: '7',
        title: 'Лапша с курицей и шафраном',
        description: 'Ароматная лапша с курицей и шафраном, идеальное сочетание для сытного обеда.',
        category: ['second-dish'],
        subcategory: ['poultry-dish'],
        image: '/src/assets/images/solyanka.jpg',
        bookmarks: 258,
        likes: 1342,
        date: '2024-03-08T00:00:00Z',
        time: '40 минут',
        portions: 4,
        nutritionValue: { calories: 400, proteins: 30, fats: 15, carbohydrates: 50 },
        ingredients: [
            { title: 'лапша', count: '200', measureUnit: 'г' },
            { title: 'курица', count: '300', measureUnit: 'г' },
            { title: 'шафран', count: '1', measureUnit: 'ч. л.' },
            { title: 'лук', count: '1', measureUnit: 'шт.' },
        ],
        steps: [
            {
                stepNumber: 1,
                description: 'Отварить лапшу.',
                image: 'url',
            },
            {
                stepNumber: 2,
                description: 'Обжарить курицу с луком и шафраном.',
                image: 'url',
            },
            {
                stepNumber: 3,
                description: 'Смешать лапшу с курицей и подавать.',
                image: 'url',
            },
        ],
    },
    {
        id: '8',
        title: 'Гриль-салат с овощами',
        description: 'Салат с обжаренными на гриле овощами и легкой заправкой.',
        category: ['salads'],
        subcategory: ['warm-salads'],
        image: '/src/assets/images/solyanka.jpg',
        bookmarks: 10,
        likes: 80,
        date: '2023-03-20T00:00:00Z',
        time: '25 минут',
        nutritionValue: { calories: 150, proteins: 4, fats: 6, carbohydrates: 20 },
        ingredients: [
            { title: 'цуккини', count: '1', measureUnit: 'шт.' },
            { title: 'болгарский перец', count: '1', measureUnit: 'шт.' },
            { title: 'баклажан', count: '1', measureUnit: 'шт.' },
            { title: 'оливковое масло', count: '0', measureUnit: 'по вкусу' },
        ],
        steps: [
            {
                stepNumber: 1,
                description: 'Обжарить овощи на гриле.',
                image: 'url',
            },
            {
                stepNumber: 2,
                description: 'Смешать с заправкой и подавать.',
                image: 'url',
            },
        ],
    },
    {
        id: '10',
        title: 'Плов по всемирно известному рецепту',
        description:
            'Вы наверняка все видео вирусный видео-мем про то, как правильно готовить плов, и вот наконец у вас появился рецепт и, соответственно, возможность насладиться данным рецептом',
        category: ['second-dish'],
        subcategory: ['snacks', 'meat', 'meat-snacks'],
        image: '/src/assets/images/plov.jpg',
        bookmarks: 8,
        likes: 15,
        date: '2025-03-28T00:00:00Z',
        time: '40 минут',
        portions: 2,
        nutritionValue: { calories: 250, proteins: 5, fats: 8, carbohydrates: 40 },
        ingredients: [
            { title: 'укроп', count: '1', measureUnit: 'шт.' },
            { title: 'кошка', count: '1', measureUnit: 'шт.' },
            { title: 'картошка', count: '25', measureUnit: 'шт.' },
            { title: 'лучше не знать? что это', count: '1', measureUnit: 'шт.' },
            { title: 'ведро воды', count: '1', measureUnit: 'шт.' },
            { title: 'охапка дров', count: '5', measureUnit: 'г' },
        ],
        steps: [
            {
                stepNumber: 1,
                description: 'Берем сначала укропу. Мелко нареазаем и тшим на медленном огне',
                image: 'url',
            },
            {
                stepNumber: 2,
                description: 'Потом добавляем кошачью попу, постоянно перемешивая.',
                image: 'url',
            },
            {
                stepNumber: 3,
                description: 'Двадцать пять картошек, нарезанных кубиком',
                image: 'url',
            },
            {
                stepNumber: 4,
                description: 'Заливаем ведров воды, размешиваем, смотрим на конститенцию.',
                image: 'url',
            },
            {
                stepNumber: 5,
                description: 'Тушить на медленном огне 30 минут.',
                image: 'url',
            },
        ],
        meat: '',
        side: 'potatoes',
    },
    {
        id: '11',
        title: 'Крабсбургер',
        description:
            'В детстве мы все смотрели Спанч-Боба. Каждый из нас мечтал попробовать это замечательное блюдо, рецептом которого так жаждал завладеть планктон. И сейч я научу вас его готовить.',
        category: ['second-dish', 'vegan'],
        subcategory: ['snacks', 'meat'],
        image: '/src/assets/images/krabsburger.webp',
        bookmarks: 100500,
        likes: 1558,
        date: '2025-04-16T00:00:00Z',
        time: '39 минут',
        portions: 2,
        nutritionValue: { calories: 260, proteins: 5, fats: 8, carbohydrates: 40 },
        ingredients: [
            { title: 'Булочка', count: '2', measureUnit: 'шт.' },
            { title: 'фарш мясной', count: '1', measureUnit: 'шт.' },
            { title: 'помидор', count: '1', measureUnit: 'шт.' },
            { title: 'сыр твердый', count: '2', measureUnit: 'шт.' },
            { title: 'соус', count: '30', measureUnit: 'мл' },
            { title: 'секретный ингридиент', count: '3', measureUnit: 'шт.' },
        ],
        steps: [
            {
                stepNumber: 1,
                description: 'обжариваем фарш в формек котлет до готовности',
                image: 'url',
            },
            {
                stepNumber: 2,
                description: 'На заранее подготовленную булочку кладем котлету и сверу помидор.',
                image: 'url',
            },
            {
                stepNumber: 3,
                description: 'Накрываем наш шедевр сыром',
                image: 'url',
            },
            {
                stepNumber: 4,
                description:
                    'Аккуратно в самый центр наливаем соус и добавляем секретный ингридиент',
                image: 'url',
            },
            {
                stepNumber: 5,
                description: 'Закрываем бургер второй булочкой. Готово.',
                image: 'url',
            },
        ],
        meat: '',
        side: 'potatoes',
    },
    {
        id: '12',
        title: 'Батино хрючево',
        description:
            'В воскресеное утро вы просыпаетесь и чувствуете, что пахнет чем-то вкусным. Вы знаете, что готовит сегодня не мама, а папа, а значит что именно вы будете есть - это загадка. Вкусная загадка, которую предстоит разгадать',
        category: ['second-dish', 'snacks', 'vegan'],
        subcategory: [
            'bread',
            'pancakes',
            'snacks',
            'grilled-beef',
            'meat',
            'meat-snacks',
            'second-dish',
        ],
        image: '/src/assets/images/batya.jpg',
        bookmarks: 50,
        likes: 17,
        date: '2025-04-01T00:00:00Z',
        time: '30 минут',
        portions: 2,
        nutritionValue: { calories: 250, proteins: 5, fats: 8, carbohydrates: 40 },
        ingredients: [
            { title: 'То, что осталось с вечера', count: '2', measureUnit: 'шт.' },
            { title: 'сосиски', count: '3', measureUnit: 'шт.' },
            { title: 'яйца', count: '2', measureUnit: 'шт.' },
            { title: 'позавчерашний салат', count: '1', measureUnit: 'шт.' },
            { title: 'вкусный соус', count: '150', measureUnit: 'мл' },
        ],
        steps: [
            {
                stepNumber: 1,
                description:
                    'Рецепт прост. Добавляем все, что у вас есть в холодильнике с вечера и перемешиваем с позавчерашним салатом',
                image: 'url',
            },
            {
                stepNumber: 2,
                description: 'на отдельной сковороде жарим яйца до готовности.',
                image: 'url',
            },
            {
                stepNumber: 3,
                description:
                    'Добавляем в яичницу сосиски и блюдо из шага №1, оюжариваем на медленном огне',
                image: 'url',
            },
            {
                stepNumber: 4,
                description: 'Перемешиваем, раскладываем по тарелками наслаждаемся.',
                image: 'url',
            },
        ],
        meat: '',
        side: 'potatoes',
    },
    {
        id: '13',
        title: 'Что-то для богатых',
        description:
            'Если вы проголодались, но вам лень готовить, есть отличный выход. Достаточно просто позволить себе сходить вресторан и заказать что угодно',
        category: ['second-dish', 'vegan'],
        subcategory: [
            'snacks',
            'meat-snacks',
            'meat-soups',
            'meat',
            'grilled-beef',
            'snacks',
            'juices',
        ],
        image: '/src/assets/images/bogataya.jpg',
        bookmarks: 50,
        likes: 17,
        date: '2025-04-01T00:00:00Z',
        time: '30 минут',
        portions: 2,
        nutritionValue: { calories: 250, proteins: 5, fats: 8, carbohydrates: 40 },
        ingredients: [
            { title: 'Деньги', count: '10000', measureUnit: 'шт.' },
            { title: 'свободное время', count: '3', measureUnit: 'по вкусу' },
            { title: 'хорошая компания', count: '4', measureUnit: 'шт.' },
            { title: 'ресторан', count: '1', measureUnit: 'шт.' },
        ],
        steps: [
            {
                stepNumber: 1,
                description: 'Собираемся хорошей компанией и выбираем ресторан',
                image: 'url',
            },
            {
                stepNumber: 2,
                description:
                    'Когда все споры окончены, можем отправиться в ресторан и выбрать, что хотим.',
                image: 'url',
            },
            {
                stepNumber: 3,
                description:
                    'Заказываем через официанта и обязательно общаемся вежливо и культурно',
                image: 'url',
            },
            {
                stepNumber: 4,
                description: 'Вкусно кушаем и благодарим за приятный вечер.',
                image: 'url',
            },
        ],
        meat: '',
        side: 'potatoes',
    },
];
